
set_property PACKAGE_PIN Y5 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property PACKAGE_PIN AB5 [get_ports miso]
set_property IOSTANDARD LVCMOS33 [get_ports miso]
set_property PACKAGE_PIN AB4 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property PACKAGE_PIN AB1 [get_ports ss]
set_property IOSTANDARD LVCMOS33 [get_ports ss]
set_property PACKAGE_PIN AB2 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]
 
set_property PACKAGE_PIN AA6 [get_ports bclk]
set_property IOSTANDARD LVCMOS33 [get_ports bclk]
set_property PACKAGE_PIN Y6 [get_ports lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports lrclk]
set_property PACKAGE_PIN Y8 [get_ports sdata]
set_property IOSTANDARD LVCMOS33 [get_ports sdata]

set_property PACKAGE_PIN U10 [get_ports {oled_dc[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_dc[0]}]
set_property PACKAGE_PIN U9 [get_ports {oled_res[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_res[0]}]
set_property PACKAGE_PIN AB12 [get_ports oled_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sclk]
set_property PACKAGE_PIN AA12 [get_ports oled_sdin]
set_property IOSTANDARD LVCMOS33 [get_ports oled_sdin]
set_property PACKAGE_PIN U11 [get_ports {oled_vbat[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_vbat[0]}]
set_property PACKAGE_PIN U12 [get_ports {oled_vdd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oled_vdd[0]}]